config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # root 'home#index'
  root 'friends#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My name is Suyogya Ratna Tamrakar..."
    @answer = 2 * 2

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control", placeholder: 'First Name' %>
  </div>
  <br />
  <div class="field form-group">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control", placeholder: 'Last Name' %>
  </div>
  <br />
  <div class="field form-group">
    <% form.label :email %>
    <%= form.email_field :email, class: "form-control", placeholder: 'Email' %>
  </div>
  <br />
  <div class="field form-group">
    <% form.label :phone %>
    <%= form.text_field :phone, class: "form-control", placeholder: 'Phone' %>
  </div>
  <br />
  <div class="field form-group">
    <% form.label :twitter %>
    <%= form.text_field :twitter, class: "form-control", placeholder: 'Twitter' %>
  </div>
  <br />
  <div class="field form-group">
    <% form.label :user_id %>
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  <br />
  <div class="actions">
    <%= form.submit class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="card">
  <div class="card-header">
    <h3>Edit Friend</h3>
  </div>
  <div class="card-body">
    <%= render 'form', friend: @friend %>
    <br/>
    <%= link_to 'Show', @friend, class: "btn btn-dark" %>
    <%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <%= link_to 'Back', friends_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <h1>Friends List</h1>
  <table class="table table-hover table-striped table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th>Added By</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <% if (friend.user == current_user) %>
          <tr>
            <td>
              <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
            </td>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>
            <td><%= friend.twitter %></td>
            <td><%= friend.user.email %></td>
            <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'Add New Friend', new_friend_path, class: 'btn btn-dark' %>
<% else %>
  <h1>This site is created from Ruby on Rails</h1>
  <p>This is my homepage. You can browse around and check my About page too.</p>
  <p>Moreover, you can have a fully functional "Friends App" and create your own user.</p>
  <p>Feel Free to Try this App</p>
<% end %>

app/views/friends/new.html.erb
<div class="card">
  <div class="card-header">
    <h3>Add New Friend</h3>
  </div>
  <div class="card-body">
    <%= render 'form', friend: @friend %>
    <br>
    <%= link_to 'Back', friends_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/friends/show.html.erb
<div class="card text-dark bg-light mb-3" style="max-width: 38rem;">
  <div class="card-header">
    <h2 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %></h2>
  </div>
  <div class="card-body">
    <p class="card-text">
      <p class="lead">
        <%= @friend.email %> |
        <%= @friend.phone %> |
        <%= @friend.twitter %>
      </p>
      <br />
      <p class="lead">
        <%= link_to 'Edit', edit_friend_path(@friend), class: 'btn btn-dark' %>
        <%= link_to 'Back', friends_path, class: 'btn btn-secondary' %>
      </p>
    </p>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friends App', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Me', home_about_path, class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item text-light">
            <%= link_to "Signed in as" + ' ' + current_user.email, edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-outline-light' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="main-body">
  <div class="row gutters-sm">
    <div class="col-md-4 mb-3">
      <div class="card">
        <div class="card-body">
          <div class="d-flex flex-column align-items-center text-center">
            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
            <div class="mt-3">
              <h4>Suyogya</h4>
              <p class="text-secondary mb-1">Full Stack Developer</p>
              <p class="text-muted font-size-sm">Asian Institute of Technology, Thailand</p>
            </div>
          </div>
        </div>
      </div>
      <div class="card mt-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><i class="bi bi-globe social-icon"></i>Website</h6>
            <span class="text-secondary">suyogyart.com.np</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><i class="bi bi-github social-icon"></i>Github</h6>
            <span class="text-secondary">Suyogyart</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><i class="bi bi-twitter social-icon" style="color: #1da1f2"></i>Twitter</h6>
            <span class="text-secondary">@Suyogyart</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><i class="bi bi-instagram social-icon" style="color: #c32aa3"></i>Instagram</h6>
            <span class="text-secondary">suyogyart</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><i class="bi bi-facebook social-icon" style="color: #1877f2"></i>Facebook</h6>
            <span class="text-secondary">suyogya.tamrakar</span>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <div class="card mb-3">
        <div class="card-header">
          <h2>About Me</h2>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Full Name</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              Suyogya Ratna Tamrakar
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Email</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              suyogya.tamrakar@gmail.com
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Phone</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              (111) 222-3333
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Mobile</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              288 288-3882
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Address</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              Asian Institute of Technology, Pathum Thani, Thailand
            </div>
          </div>
        </div>
      </div>
      <div class="row gutters-sm">
        <div class="col-sm-6 mb-3">
          <div class="card h-100">
            <div class="card-body">
              <h6 class="d-flex align-items-center mb-3"><i class="bi bi-app-indicator icon"></i>App Development Skills</h6>
              <small>Ruby on Rails</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Java Spring Boot</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>iOS Native</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Android Native</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 35%" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Mobile Hybrid</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 mb-3">
          <div class="card h-100">
            <div class="card-body">
              <h6 class="d-flex align-items-center mb-3"><i class="bi bi-terminal-fill icon"></i>Programming Skills</h6>
              <small>Ruby</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Java</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Python</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 83%" aria-valuenow="83" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>HTML, CSS, JS</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Swift</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 86%" aria-valuenow="86" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Kotlin</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 36%" aria-valuenow="36" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small>Dart</small>
              <div class="progress mb-3" style="height: 5px">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 38%" aria-valuenow="38" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>This site is created from Ruby on Rails</h1>
<p>This is my homepage. You can browse around and check my About page too.</p>
<p>Moreover, you can have a fully functional "Friends App" and create your own user.</p>
<p>Feel Free to Try this App</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <title>Friends App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br />
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>